cloud_provider: external
external_cloud_provider: openstack
# enabled add-ons
metallb_enabled: true
cert_manager_enabled: true
ingress_nginx_enabled: true
argocd_enabled: true
metrics_server_enabled: true
# disabled add-ons (should be filtered out of the report)
aws_ebs_csi_enabled: false
azure_csi_enabled: false
